# Generated by Django 4.0.5 on 2022-06-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('JordanCare', 'Jordancare'), ('Sauron_Health', 'Sauron Health'), ('Delay The Inevitable', 'Delay The Inevitable'), ('Florida Guns & Medicine', 'Florida Guns And Medicine'), ('SithCare', 'Sithcare'), ('Waffle House', 'Waffle House'), ('For Rich People Only', 'For Rich People Only')], default='JordanCare', max_length=50)),
                ('accountHolder', models.CharField(max_length=32)),
                ('policyNumber', models.IntegerField()),
                ('idNumber', models.IntegerField()),
            ],
        ),
    ]
