# Generated by Django 4.0.5 on 2022-06-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('reason', models.CharField(choices=[('Plastic Surgery', 'Cosmetic'), ('Necromancy', 'Death'), ('Allergies', 'Normal'), ('Jerusalem Syndrome', 'Religious'), ('Ate too much', 'Foolish')], default='Plastic Surgery', max_length=50)),
                ('details', models.CharField(max_length=500)),
            ],
        ),
    ]
