# Generated by Django 4.0.5 on 2022-06-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(choices=[('Plastic Surgery', 'Plastic Surgery'), ('Necromancy', 'Necromancy'), ('Allergies', 'Allergies'), ('Jerusalem Syndrome', 'Jerusalem Syndrome'), ('Ate too much', 'Ate Too Much')], default='Plastic Surgery', max_length=50),
        ),
    ]
