# Generated by Django 4.0.5 on 2022-06-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='physician',
            field=models.CharField(choices=[('Jordan Bank', 'Jordan Bank'), ('Meiling Li', 'Meiling Li'), ('Tyger Salters', 'Tyger Salters'), ('Ofori Manson', 'Ofori Manson'), ('Kevin Ha', 'Kevin Ha'), ('Jean Eng', 'Jean Eng'), ('Rafay Hassan', 'Rafay Hassan')], default='Jordan Bank', max_length=50),
        ),
    ]
